name: Pull Request Workflow

# global environment variables to all jobs
env: 
  REGION: us-west-2
  SOLUTION_NAME: aws-media-services-application-mapper
  DIST_OUTPUT_BUCKET: msam-pr-build
on: 
  pull_request:
    types: [opened, edited, reopened]

jobs:
  scan-build-upload-job:
    runs-on: ubuntu-latest
    # use a specific environment for this build that has secrets defined and protection rules in place, if needed
    environment: pull_request_env
    steps:
      - name: Update system path
        run: echo "${{ secrets.TEST_SECRET }}"
